?!?!?

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -30,12 +30,21 @@ jobs:
     - name: Apply Prettier
       run: npx prettier --write "**/*.java"
 
-    - name: Commit changes
+    - name: Check for Changes
+      id: git-check
       run: |
-        git config --global user.name 'github-actions'
-        git config --global user.email 'github-actions@github.com'
-        git add .
-        git commit -m 'Apply Prettier format' || echo "No changes to commit"
-        git push origin "${GITHUB_HEAD_REF}"
+        git diff --exit-code || echo "Changes detected"
+      continue-on-error: true
+
+    - name: Commit changes
+      if: steps.git-check.outcome == 'success'
+        run: |
+          git config --global user.name 'github-actions'
+          git config --global user.email 'github-actions@github.com'
+          git add .
+          git commit -m 'Apply Prettier format' || echo "No changes to commit"
+          git push origin "${GITHUB_HEAD_REF}"
+      else:
+        echo "No Formatting Required"
       env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
